### ISSUE TITLE
Swagger generation

### ISSUE THREAD

**Issue by marcinphero** [balmbees/corgi#50]
Hi

How to generate Swagger file from existing routes?

The link is not working:
https://github.com/balmbees/corgi/blob/master/src/__test__/swagger_spec.ts

**Comment by breath103** [comment]
Hi, Sorry for late notice. You can look into https://github.com/balmbees/corgi/blob/master/src/swagger/__test__/index_spec.ts this test for full example!
Especially https://github.com/balmbees/corgi/blob/master/src/swagger/__test__/index_spec.ts#L148 part is the trick -- mount [all routes + SwaggerRoute(all routes)]

**Comment by marcinphero** [comment]
Thank you !

Btw you could add support for PATCH method :)

**Comment by breath103** [comment]
sure it would be quite easy :) 
i didn't considered it only because i haven't had situation where i need PATCH method
can you share your needs about PATCH method and usecase?

**Comment by marcinphero** [comment]
I'm building API on AWS lambda based on corgi. Using PATCH is only for having nice code :). I read about difference https://stackoverflow.com/questions/28459418/rest-api-put-vs-patch-with-real-life-examples and wanted to use it right.

**Comment by breath103** [comment]
hm ok that seems legit :) i'll implement very general / standard form of patch method, https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH which won't be very different from PUT / POST anyway technically, (but quite different semantically)

**Comment by breath103** [comment]
https://github.com/balmbees/corgi/issues/51
