### ISSUE TITLE
Does it work with aws-sam?

### ISSUE THREAD

**Issue by therepo90** [balmbees/corgi#55]
Nice lib - does it work with aws-sam ? I mean if so -  can you provide template.yaml configuration for aws-sam with API gateway proxy?

**Comment by breath103** [comment]
Hi @therepo90, this library simply provides a way to structurize Lambda function. in other words, as long as you use API Gateway + Lambda Proxy, regardless of deployment platform (serverless framework / AWS-SAM....) it should work. 

for example, you can just use any SAM template using API Gateway Proxy, such as https://github.com/floodfx/aws-lambda-proxy-using-sam-local
than change https://github.com/floodfx/aws-lambda-proxy-using-sam-local/blob/master/index.js this file into
```
exports.handler = new Router([....]).handler();
```
that's it :)

**Comment by breath103** [comment]
closing because of a rack of response @therepo90
